channels:
    - defaults
    - conda-forge
    - pytorch
    dependencies:
    - python=3.8.2
    - pytorch=1.6.0
    - pytorch-lightning
    - torchvision=0.7.0
    - pip
    - pip:
      - mlflow
      - transformers
      - torchtext